# Generated by Django 5.2.8 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight_value',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('packet', 'packet')], default='g', max_length=10),
        ),
    ]
